### PR TITLE
More usable props.

### PR DESCRIPTION
**Pull request by Keno-GH**
Took me a bit longer than I thought. Here is a summary of the changes I did:

Vanilla storage

- Wooden Logs and Large Wooden Logs now are wood storage.
- Empty weapon rack, Swords weapon rack and Spear weapon rack are now weapons storage. The Swords and Spears one hide the contents. They are slightly beautiful.
- Empty armor stand and Full armor stand are now apparel storage (intended for armor). The full one hides the contents. They are slightly beautiful.
- Wooden chest and Large wooden chest are now general purpose storage.
- The wagon is now a general purpose storage. It hides the contents because of it's big footprint. The items would be on top of the handle if the contents were visible.
- Small wooden box, Large wooden box and Pallet with wooden boxes are now general purpose storage.
- Small cardboard box, Large cardboard box and Pallet with cardboard are now loose items storage like the granary. They are cheaper than the wooden boxes and hold one stack more, at the cost of variety.
- Large pallet is now a dump storage like the LMW's Deep Storage pallet. They will work as 2x2 Pallet.
- The Tall Cabinet is now stuffable. It can store food items like the granary. It is better in every way than the food basket.
- The Locker is now stuffable. It can store apparel. It can store heavier clothing than the clothing racks.
- Empty warehouse shelf is now a dump storage like the pallet. It is better than the pallet. The texture is not stuffable.
- Warehouse shelf with boxes is now a general purpose storage. It is better than the tall shelves.
- The vending machines can store foods and drugs. They are better used with Hospitality visitor when allowed to buy in an area where the vending machines are.
- Concrete bags are now plant matter. It's very efficient.

Dubs Bad Hygiene

- The water bucket is now an alternative to the water tub
- The water tank is now an alternative to the water butt
- The water dispenser is now an alternative to a fountain

Fertile fields

- Concrete bags can store loose things like dirt, sand and fertilizer.

Rimatomics

- The toxic waste barrel is now a nuclear waste storage. Efficient for it's simple purpose.

Rimfridge

- The fridge (from kitchen props) is now a food storage like the deep fridge. It is faster to make and easier to use than the deep fridge, but less power efficient.

### CODE REVIEW

**Comment by DrZhivago1** [comment]
Cool, I give it a look over and we'll get it included for the next update.

**Comment by Keno-GH** [comment]
I am a bit sad to hear that you are removing specified storage, but it's totally understandable.

**Comment by DrZhivago1** [comment]
You did pretty good. Missed one dependency in the patch for RimFridge, and I removed some excess fields that we'll no longer need b/c I also changed the inheratence for all items. As I said, I've also removed specified storage. Yes it allows for unrealistic possibility. However given the greater benefit of mod compatibility, and the options in-game for players to restrict/allow whatever they want with settings, it's a good trade-off.

That being said, the way you've setup this PR is difficult. You moved a lot of files and that causes me to not be able to smoothly transition the file for a merge. Also your file was not pulled from the lastest master, so the changes that *should* be there were not, which again just takes more time to review. Finally I'm not allowed to edit anything, which is fair. However it doesn't let me merge either because I can't update it to my standard.

So I'm going to drop the new file here and if you overwrite your branch with it I will pull it into Master. That's just to keep track of your credit.
[VFE_Usable_Props.zip](https://github.com/DrZhivago1/DocWorld/files/5443370/VFE_Usable_Props.zip)

**Comment by DrZhivago1** [comment]
Idk how to resolve this shit so fuck it lol

**Comment by Keno-GH** [comment]
Just copy and paste the new code. I started working with an earlier version of VFE_Usable_props.xml because it got updated while I was working on it. But I documented every change.

**Comment by DrZhivago1** [comment]
Yea I've got the changes incorporated. I just accidentally overwrote some new stuff I was working on that I hadn't pushed yet so I'm trying to do some recovery.

**Pull request closed without merging**
